// Code generated by "stringer -type=Level -linecomment"; DO NOT EDIT.

package logger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LevelOff-0]
	_ = x[LevelFatal-1]
	_ = x[LevelError-2]
	_ = x[LevelWarn-3]
	_ = x[LevelInfo-4]
	_ = x[LevelDebug-5]
	_ = x[LevelTrace-6]
}

const _Level_name = "OFFFATALERRORWARNINFODEBUGTRACE"

var _Level_index = [...]uint8{0, 3, 8, 13, 17, 21, 26, 31}

func (i Level) String() string {
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
